#ifndef PARSEC_REGEX_NODES_HEADER
#define PARSEC_REGEX_NODES_HEADER

#include "Utils.hpp"

#include <ostream>
#include <memory>
#include <vector>

namespace parsec {
	class RegExTraverser;
	class RegExChar;

	/** @brief List of pointers to @ref RegExChar "RegExChars". */
	using RegExCharList = std::vector<const RegExChar*>;

	/**
	 * @brief Polymorphic entry point to the tree representation of a regular expression.
	 */
	class RegExNode {
	public:
		/** @brief Print a node to a @c std::ostream. */
		friend std::ostream& operator<<(std::ostream& out, const RegExNode& n);

		/** @{ */
		RegExNode(const RegExNode&) = delete;
		RegExNode& operator=(const RegExNode&) = delete;
		/** @} */

		/** @{ */
		RegExNode(RegExNode&&) = delete;
		RegExNode& operator=(RegExNode&&) = delete;
		/** @} */

		/** @{ */
		/** @copybrief */
		virtual ~RegExNode() = default;
		/** @} */

		/** @{ */
		/** @brief Traverse the regex tree in a type-safe manner using the specified RegExTraverser. */
		virtual void TraverseWith(RegExTraverser& traverser) const = 0;

		/** @brief Check if the node can generate an empty string. */
		virtual bool IsNullable() const noexcept = 0;

		/** @brief Make the exact copy of the node. */
		virtual std::unique_ptr<RegExNode> Clone() const = 0;
		/** @} */

		/** @{ */
		/** @brief Set a new parent node for the node. */
		void SetParent(const RegExNode* parent) noexcept {
			this->parent = parent; 
		}

		/** @brief Get the parent node of the node. */
		const RegExNode* GetParent() const noexcept {
			return parent;
		}
		/** @} */

		/** @{ */
		/** @brief Make the list of RegExChar nodes that can take the first position in the string generated by the node. */
		RegExCharList GetFirstPos() const;
		
		/** @brief Make the list of RegExChar nodes that can take the last position in the string generated by the node. */
		RegExCharList GetLastPos() const;
		/** @} */

	protected:
		/** @copybrief */
		RegExNode() = default;

	private:
		const RegExNode* parent = nullptr;
	};



	/**
	 * @brief Literal character regular expression.
	 */
	class RegExChar : public RegExNode {
	public:
		/** @{ */
		/** @brief Construct a new RegExChar node with a value. */
		explicit RegExChar(char value) noexcept
		 : value(value)
		{ }

		/** @copybrief */
		~RegExChar() = default;
		/** @} */

		/** @{ */
		void TraverseWith(RegExTraverser& traverser) const override;

		bool IsNullable() const noexcept override {
			return false;
		}

		std::unique_ptr<RegExNode> Clone() const override {
			return std::make_unique<RegExChar>(value);
		}
		/** @} */

		/** @{ */
		/** @brief Get the value of the node. */
		char GetValue() const noexcept {
			return value;
		}

		/** @brief Make the list of RegExChar nodes that can take the position after this node. */
		RegExCharList GetFollowPos() const;
		/** @} */

	private:
		char value;
	};



	/**
	 * @brief Empty expression.
	 */
	class RegExNil : public RegExNode {
	public:
		/** @{ */
		/** @copybrief */
		RegExNil() = default;

		/** @copybrief */
		~RegExNil() = default;
		/** @} */

		/** @{ */
		void TraverseWith(RegExTraverser& traverser) const override;

		bool IsNullable() const noexcept override {
			return true;
		}
		
		std::unique_ptr<RegExNode> Clone() const override {
			return std::make_unique<RegExNil>();
		}
		/** @} */
	};



	/**
	 * @brief Optional expression.
	 */
	class RegExOpt : public RegExNode {
	public:
		/** @{ */
		/** @brief Construct a new RegExOpt node with a single child node. */
		explicit RegExOpt(std::unique_ptr<RegExNode> expr) noexcept
		 : innerExpr(std::move(expr)) {
			innerExpr->SetParent(this);
		}

		/** @copybrief */
		~RegExOpt() = default;
		/** @} */

		/** @{ */
		void TraverseWith(RegExTraverser& traverser) const override;

		bool IsNullable() const noexcept override {
			return true;
		}

		std::unique_ptr<RegExNode> Clone() const override {
			return std::make_unique<RegExOpt>(innerExpr->Clone());
		}
		/** @} */

		/** @{ */
		/** @brief Get the child node of the node. */
		const RegExNode& GetChild() const noexcept {
			return *innerExpr;
		}
		/** @} */
		
	private:
		std::unique_ptr<RegExNode> innerExpr;
	};



	/**
	 * @brief Kleene plus expression.
	 */
	class RegExPlus : public RegExNode {
	public:
		/** @{ */
		/** @brief Construct a new RegExPlus node with a single child node. */
		explicit RegExPlus(std::unique_ptr<RegExNode> expr) noexcept
		 : innerExpr(std::move(expr)) {
			innerExpr->SetParent(this);
		}

		/** @copybrief */
		~RegExPlus() = default;
		/** @} */

		/** @{ */
		void TraverseWith(RegExTraverser& traverser) const override;

		bool IsNullable() const noexcept override {
			return false;
		}

		std::unique_ptr<RegExNode> Clone() const override {
			return std::make_unique<RegExPlus>(innerExpr->Clone());
		}
		/** @} */

		/** @{ */
		/** @brief Get the child node of the node. */
		const RegExNode& GetChild() const noexcept {
			return *innerExpr;
		}
		/** @} */
		
	private:
		std::unique_ptr<RegExNode> innerExpr;
	};



	/**
	 * @brief Kleene star expression.
	 */
	class RegExStar : public RegExNode {
	public:
		/** @{ */
		/** @brief Construct a new RegExStar node with a single child node. */
		explicit RegExStar(std::unique_ptr<RegExNode> expr) noexcept
		 : innerExpr(std::move(expr)) {
			innerExpr->SetParent(this);
		}

		/** @copybrief */
		~RegExStar() = default;
		/** @} */

		/** @{ */
		void TraverseWith(RegExTraverser& traverser) const override;

		bool IsNullable() const noexcept override {
			return true;
		}

		std::unique_ptr<RegExNode> Clone() const override {
			return std::make_unique<RegExStar>(innerExpr->Clone());
		}
		/** @} */

		/** @{ */
		/** @brief Get the child node of the node. */
		const RegExNode& GetChild() const noexcept {
			return *innerExpr;
		}
		/** @} */
		
	private:
		std::unique_ptr<RegExNode> innerExpr;
	};



	/**
	 * @brief Alternation expression.
	 */
	class RegExAltern : public RegExNode {
	public:
		/** @{ */
		/** @brief Construct a new RegExAltern node with two child nodes. */
		RegExAltern(std::unique_ptr<RegExNode> left, std::unique_ptr<RegExNode> right) noexcept
		 : leftExpr(std::move(left)), rightExpr(std::move(right)) {
			leftExpr->SetParent(this);
			rightExpr->SetParent(this);
		}

		/** @copybrief */
		~RegExAltern() = default;
		/** @} */

		/** @{ */
		void TraverseWith(RegExTraverser& traverser) const override;

		bool IsNullable() const noexcept override {
			return leftExpr->IsNullable() || rightExpr->IsNullable();
		}

		std::unique_ptr<RegExNode> Clone() const override {
			return std::make_unique<RegExAltern>(leftExpr->Clone(), rightExpr->Clone());
		}
		/** @} */

		/** @{ */
		/** @brief Get the left child of the node. */
		const RegExNode& GetLeftChild() const noexcept {
			return *leftExpr;
		}

		/** @brief Get the right child of the node. */
		const RegExNode& GetRightChild() const noexcept {
			return *rightExpr;
		}
		/** @} */

	private:
		std::unique_ptr<RegExNode> leftExpr, rightExpr;
	};



	/**
	 * @brief Concatenation expression.
	 */
	class RegExConcat : public RegExNode {
	public:
		/** @{ */
		/** @brief Construct a new RegExConcat node with two child nodes. */
		RegExConcat(std::unique_ptr<RegExNode> left, std::unique_ptr<RegExNode> right) noexcept
		 : leftExpr(std::move(left)), rightExpr(std::move(right)) {
			leftExpr->SetParent(this);
			rightExpr->SetParent(this);
		}

		/** @copybrief */
		~RegExConcat() = default;
		/** @} */

		/** @{ */
		void TraverseWith(RegExTraverser& traverser) const override;
		
		bool IsNullable() const noexcept override {
			return leftExpr->IsNullable() && rightExpr->IsNullable();
		}

		std::unique_ptr<RegExNode> Clone() const override {
			return std::make_unique<RegExConcat>(leftExpr->Clone(), rightExpr->Clone());
		}
		/** @} */

		/** @{ */
		/** @brief Get the left child of the node. */
		const RegExNode& GetLeftChild() const noexcept {
			return *leftExpr;
		}

		/** @brief Get the right child of the node. */
		const RegExNode& GetRightChild() const noexcept {
			return *rightExpr;
		}
		/** @} */

	private:
		std::unique_ptr<RegExNode> leftExpr, rightExpr;
	};



	/**
	 * @brief Provides a mechanism for traversing regular expressions using the visitor pattern.
	 */
	class RegExTraverser {
	public:
		/** @{ */
		/** @brief Called for a RegExChar node. */
		virtual void VisitNode(const RegExChar& n) = 0;

		/** @brief Called for a RegExOpt node. */
		virtual void VisitNode(const RegExOpt& n) = 0;

		/** @brief Called for a RegExNil node. */
		virtual void VisitNode(const RegExNil& n) = 0;

		/** @brief Called for a RegExPlus node. */
		virtual void VisitNode(const RegExPlus& n) = 0;

		/** @brief Called for a RegExStar node. */
		virtual void VisitNode(const RegExStar& n) = 0;

		/** @brief Called for a RegExAltern node. */
		virtual void VisitNode(const RegExAltern& n) = 0;

		/** @brief Called for a RegExConcat node. */
		virtual void VisitNode(const RegExConcat& n) = 0;
		/** @} */

		/** @{ */
		/** @brief Defines the order in which the traverser visits child nodes. */
		virtual TraversalTypes GetTraversalType() const noexcept {
			return TraversalTypes::None;
		} 
		/** @} */

	protected:
		/** @{ */
		/** @copybrief */
		RegExTraverser() = default;

		/** @copybrief */
		~RegExTraverser() = default;
		/** @} */

		/** @{ */
		RegExTraverser(const RegExTraverser&) = default;
		RegExTraverser& operator=(const RegExTraverser&) = default;
		/** @} */

		/** @{ */
		RegExTraverser(RegExTraverser&&) = default;
		RegExTraverser& operator=(RegExTraverser&&) = default;
		/** @} */
	};
}

#endif